
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/properties.properties to edit this template

# Shop ID: 8-digits shop ID provided in your Back Office (Menu: Settings > Shop > REST API keys).
site_id=[CHANGE_ME]

# Test password: Provided in your Back Office (Menu: Settings > Shop > REST API keys).
key_test=[CHANGE_ME]

# Production password: provided in your Back Office (Menu: Settings > Shop > REST API keys).
key_prod=[CHANGE_ME]
