
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/properties.properties to edit this template

# Shop ID: 8-digits shop ID provided in your Back Office (Menu: Settings > Shop > Keys).
site_id=12345678

# Test key: Provided in your Back Office (Menu: Settings > Shop > Keys).
key_test=1111111111111111

# Production key: provided in your Back Office (Menu: Settings > Shop > Keys).
key_prod=2222222222222222
