
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/properties.properties to edit this template

# Shop ID: 8-digits shop ID provided in your Back Office (Menu: Settings > Shop > Keys).
site_id=21359648

# Test key: Provided in your Back Office (Menu: Settings > Shop > Keys).
key_test=testpassword_m8R9MtLSxQFX1uuOnKDvDeZQDJsqGjLxup1dfgeUCPJUB

# Production key: provided in your Back Office (Menu: Settings > Shop > Keys).
key_prod=2222222222222222
